### ISSUE TITLE
モデルを設計する

### ISSUE THREAD

**Issue by Shikugawa** [MISW/Pictorium#3]

**Comment by Shikugawa** [comment]
draw.io使おう

**Comment by musaprg** [comment]
@Shikugawa OK とりあえず必要そうなデータを洗い出したほうがいいかしらね

**Comment by musaprg** [comment]
## User
ユーザidやパスワードなど個人に関係するもの
- email
- user_id
- pass
- HN
- 所属
## Art
作品に関係するもの
- 評価
- ブックマーク
- コメント

**Comment by Shikugawa** [comment]
@musaprg コメンド、タグは別モデルで管理したほうがいい、あとユーザー関連もdeviseで管理する所とその他の属性情報を管理するモデルに分離したほうが良さげ

**Comment by Shikugawa** [comment]
設計した
