### ISSUE TITLE
CI環境の整備

### ISSUE THREAD

**Issue by musaprg** [MISW/Pictorium#7]

**Comment by musaprg** [comment]
WerckerかTravis CIのどっちかだけどどうしよう（OSSで比較的使われてるっていうイメージ強いのはTravisだしこの際Travisにしたほうがいいかも）

**Comment by Shikugawa** [comment]
間を取ってCircle CI(適当)

**Comment by musaprg** [comment]
@Shikugawa 俺も同意 Travisでいきましょ
